-- ENUMS
drop type if exists public.user_role;
create type public.user_role as enum ('USER', 'ADVERTISER');

drop type if exists public.ad_status;
create type public.ad_status as enum ('active', 'inactive', 'draft', 'expired');

drop type if exists public.media_type;
create type public.media_type as enum ('image', 'video');

-- TABLES
-- Table: locations
drop table if exists public.locations cascade;
create table if not exists public.locations (
    id bigint generated by default as identity primary key,
    name text not null,
    type text not null, -- 'country', 'region', 'subregion'
    parent_id bigint references public.locations(id),
    code text, -- ISO code for countries, etc.
    phone_code text,
    slug text unique
);
comment on table public.locations is 'Stores location data like countries, regions, and cities.';

-- Table: categories
drop table if exists public.categories cascade;
create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    name text not null
);
comment on table public.categories is 'Stores ad categories.';

-- Table: profiles
drop table if exists public.profiles cascade;
create table if not exists public.profiles (
  id uuid not null primary key,
  updated_at timestamptz,
  username text unique,
  full_name text,
  avatar_url text,
  role user_role default 'USER'::user_role,
  country_id bigint references public.locations(id),
  contact_email text,
  contact_whatsapp text,
  contact_telegram text,
  contact_social_url text,

  constraint username_length check (char_length(username) >= 3),
  foreign key (id) references auth.users(id) on delete cascade
);
comment on table public.profiles is 'Profile data for each user.';
alter table public.profiles enable row level security;

-- Table: ads
drop table if exists public.ads cascade;
create table if not exists public.ads (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    title text not null,
    description text not null,
    category_id bigint not null references public.categories(id),
    country_id bigint references public.locations(id),
    region_id bigint references public.locations(id),
    subregion_id bigint references public.locations(id),
    status ad_status not null default 'draft',
    created_at timestamptz default now(),
    updated_at timestamptz,
    boosted_until timestamptz,
    slug text not null unique,
    tags text[] null
);
comment on table public.ads is 'Stores classified ads posted by users.';
alter table public.ads enable row level security;

-- Table: ad_media
drop table if exists public.ad_media cascade;
create table if not exists public.ad_media (
    id bigint generated by default as identity primary key,
    ad_id bigint not null references public.ads(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    url text not null,
    type media_type not null,
    is_cover boolean not null default false,
    created_at timestamptz default now()
);
comment on table public.ad_media is 'Stores media files (images, videos) associated with ads.';
alter table public.ad_media enable row level security;


-- FUNCTIONS AND TRIGGERS
-- Function to create a profile for a new user
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, username, role)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'username',
    (new.raw_user_meta_data->>'role')::user_role
  );
  return new;
end;
$$;

-- Trigger to execute the function on new user creation
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- STORAGE
-- Bucket: avatars
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 2097152, '{"image/jpeg","image/png","image/webp"}')
on conflict (id) do nothing;

-- Bucket: ad_media
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('ad_media', 'ad_media', true, 52428800, '{"image/jpeg","image/png","image/webp","video/mp4","video/quicktime"}')
on conflict (id) do nothing;


-- ROW LEVEL SECURITY (RLS) POLICIES
--
-- PROFILES RLS
--
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone."
  ON public.profiles FOR SELECT
  USING ( true );

DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
CREATE POLICY "Users can insert their own profile."
  ON public.profiles FOR INSERT
  WITH CHECK ( auth.uid() = id );

DROP POLICY IF EXISTS "Users can update their own profile." ON public.profiles;
CREATE POLICY "Users can update their own profile."
  ON public.profiles FOR UPDATE
  USING ( auth.uid() = id )
  WITH CHECK ( auth.uid() = id );

--
-- ADS RLS
--
DROP POLICY IF EXISTS "Ads are public if active." ON public.ads;
CREATE POLICY "Ads are public if active."
  ON public.ads FOR SELECT
  USING ( status = 'active' );

DROP POLICY IF EXISTS "Advertisers can see their own ads regardless of status." ON public.ads;
CREATE POLICY "Advertisers can see their own ads regardless of status."
  ON public.ads FOR SELECT
  USING ( auth.uid() = user_id );

DROP POLICY IF EXISTS "Advertisers can create their own ads." ON public.ads;
CREATE POLICY "Advertisers can create their own ads."
  ON public.ads FOR INSERT
  WITH CHECK (
    auth.uid() = user_id AND
    (select role from public.profiles where id = auth.uid()) = 'ADVERTISER'
  );

DROP POLICY IF EXISTS "Advertisers can update their own ads." ON public.ads;
CREATE POLICY "Advertisers can update their own ads."
  ON public.ads FOR UPDATE
  USING ( auth.uid() = user_id )
  WITH CHECK (
    auth.uid() = user_id AND
    (select role from public.profiles where id = auth.uid()) = 'ADVERTISER'
  );

DROP POLICY IF EXISTS "Advertisers can delete their own ads." ON public.ads;
CREATE POLICY "Advertisers can delete their own ads."
  ON public.ads FOR DELETE
  USING ( auth.uid() = user_id );

--
-- AD_MEDIA RLS
--
DROP POLICY IF EXISTS "Media is public." ON public.ad_media;
CREATE POLICY "Media is public."
  ON public.ad_media FOR SELECT
  USING ( true );

DROP POLICY IF EXISTS "Advertisers can insert media for their ads." ON public.ad_media;
CREATE POLICY "Advertisers can insert media for their ads."
  ON public.ad_media FOR INSERT
  WITH CHECK ( auth.uid() = user_id );

DROP POLICY IF EXISTS "Advertisers can delete their own media." ON public.ad_media;
CREATE POLICY "Advertisers can delete their own media."
  ON public.ad_media FOR DELETE
  USING ( auth.uid() = user_id );

--
-- STORAGE RLS
--
-- Avatars Bucket
DROP POLICY IF EXISTS "Avatar images are publicly accessible." ON storage.objects;
CREATE POLICY "Avatar images are publicly accessible."
    ON storage.objects FOR SELECT
    USING ( bucket_id = 'avatars' );

DROP POLICY IF EXISTS "Anyone can upload an avatar." ON storage.objects;
CREATE POLICY "Anyone can upload an avatar."
    ON storage.objects FOR INSERT
    WITH CHECK ( bucket_id = 'avatars' );

DROP POLICY IF EXISTS "Users can update their own avatar." ON storage.objects;
CREATE POLICY "Users can update their own avatar."
    ON storage.objects FOR UPDATE
    USING ( auth.uid() = owner )
    WITH CHECK ( bucket_id = 'avatars' );

-- Ad Media Bucket
DROP POLICY IF EXISTS "Ad media is publicly accessible." ON storage.objects;
CREATE POLICY "Ad media is publicly accessible."
    ON storage.objects FOR SELECT
    USING ( bucket_id = 'ad_media' );

DROP POLICY IF EXISTS "Advertisers can upload media." ON storage.objects;
CREATE POLICY "Advertisers can upload media."
    ON storage.objects FOR INSERT
    WITH CHECK (
      bucket_id = 'ad_media' AND
      (select role from public.profiles where id = auth.uid()) = 'ADVERTISER'
    );

DROP POLICY IF EXISTS "Advertisers can delete their own media files." ON storage.objects;
CREATE POLICY "Advertisers can delete their own media files."
    ON storage.objects FOR DELETE
    USING (
      bucket_id = 'ad_media' AND
      auth.uid() = owner
    );

-- DUMMY DATA --
-- Insert Categories
insert into public.categories (name) values
  ('Scorts'),
  ('Chicas Trans'),
  ('Scorts Gay'),
  ('Servicios Virtuales'),
  ('Masajes')
on conflict do nothing;

-- Insert Locations
-- Countries
insert into public.locations (id, name, type, parent_id, code, phone_code, slug) values
(1, 'Colombia', 'country', null, 'CO', '57', 'colombia')
on conflict do nothing;

-- Regions (Departments of Colombia)
insert into public.locations (id, name, type, parent_id, slug) values
(101, 'Antioquia', 'region', 1, 'antioquia'),
(102, 'Cundinamarca', 'region', 1, 'cundinamarca'),
(103, 'Valle del Cauca', 'region', 1, 'valle-del-cauca')
on conflict do nothing;

-- Subregions (Cities)
insert into public.locations (id, name, type, parent_id, slug) values
(10101, 'Medellin', 'subregion', 101, 'medellin'),
(10201, 'Bogota', 'subregion', 102, 'bogota'),
(10301, 'Cali', 'subregion', 103, 'cali')
on conflict do nothing;
